name: Integration Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-22.04
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: "password"
        ports:
          - 5432:5432
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: "1.20"
      - uses: actions/checkout@v3
      - name: copy over config
        run: sudo mkdir -p /etc/eve/tls && sudo cp build/config.toml.ci /etc/eve/config.toml
      - name: Build
        run: make
      - name: sql migration
        run: |
          go install github.com/pressly/goose/v3/cmd/goose@latest
          cd sql
          ~/go/bin/goose postgres postgres://postgres:password@localhost:5432/postgres up
      - name: Integration test
        run: sudo ./bin/eve-tools && sudo make integration-test
