name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD="password"
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v3

    - name: copy over config
      run: mkdir /etc/eve && cp config.toml.ci /etc/eve/config.toml

    - name: Build
      run: make

    - name: Run test
      run: make test

    - name: Start eve
      run: make start
