name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: "password"
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v3

    - name: copy over config
      run: sudo mkdir /etc/eve && sudo cp config.toml.ci /etc/eve/config.toml

    - name: Build
      run: make

    - name: debug
      run: ls

    - name: sql
      run: |
        go install github.com/pressly/goose/v3/cmd/goose@latest
        ~/go/bin/goose postgres postgres://postgres:password@localhost:5432/postgres up

    - name: Start eve and test
      run: make start& sleep 10 && make test
