name: Unit Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        go-version: ["1.19", "1.20"]
    steps:
      - uses: actions/checkout@v3
      - name: Unit test
        run: make unit-test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
